version: '3.1'

services:

  angular-front:
    container_name: index-angular-prod
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 4200:4200