version: '3.1'

services:

  angular-front:
    container_name: jurilog-angular-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    volumes:
      - /app
      - /app/node_modules
    ports:
      - 80:80